import { MenuItem } from './menu.model';

export const MENU: MenuItem[] = [
  {
    id: 1,
    label: 'MENUITEMS.MENU.TEXT',
    isTitle: true,
  },
  {
    id: 2,
    label: 'MENUITEMS.DASHBOARD.TEXT',
    icon: 'ti ti-home',
    subItems: [
      {
        id: 3,
        label: 'MENUITEMS.DASHBOARD.LIST.ANALYTICS',
        link: '/',
        parentId: 2,
      },
      {
        id: 5,
        label: 'MENUITEMS.DASHBOARD.LIST.ECOMMERCE',
        link: '/ecommerce',
        parentId: 2,
      },
    ],
  },
  {
    id: 24,
    label: 'MENUITEMS.APPS.LIST.ADDRESS',
    icon: 'ti ti-map-pin',
    subItems: [
      {
        id: 1,
        label: 'MENUITEMS.APPS.LIST.COUNTRIES',
        link: '/apps/countries',
        parentId: 24,
      },
      {
        id: 2,
        label: 'MENUITEMS.APPS.LIST.CITIES',
        link: '/apps/cities',
        parentId: 24,
      },
      {
        id: 3,
        label: 'MENUITEMS.APPS.LIST.SHIPMENTS',
        link: '/apps/shipments',
        parentId: 24,
      },
      {
        id: 4,
        label: 'MENUITEMS.APPS.LIST.ADDRESS',
        link: '/apps/addreeses',
        parentId: 24,
      },
    ],
  },
  {
    id: 10,
    label: 'MENUITEMS.APPS.LIST.SIDEBARBANNER',
    icon: 'ti ti-layout-sidebar-right',
    link: '/apps/ad-side-bar-banners',
    parentId: 8,
  },
  {
    id: 23,
    label: 'MENUITEMS.APPS.LIST.CATEGORIES',
    icon: 'ti ti-list-check',
    link: '/apps/categories',
    parentId: 8,
  },
  {
    id: 23,
    label: 'MENUITEMS.APPS.LIST.CERTIFICATIONS',
    icon: 'ti ti-certificate',
    link: '/apps/certifications',
    parentId: 8,
  },
  {
    id: 23,
    label: 'MENUITEMS.APPS.LIST.CLIENTS',
    icon: 'ti ti-users',
    link: '/apps/clients',
    parentId: 8,
  },
  {
    id: 23,
    label: 'MENUITEMS.APPS.LIST.CONTACTS',
    icon: 'ti ti-address-book',
    link: '/apps/contacts',
    parentId: 8,
  },
  {
    id: 11,
    label: 'MENUITEMS.APPS.LIST.COUPONS',
    icon: 'ti ti-tag',
    link: '/apps/coupons',
    parentId: 8,
  },
  {
    id: 2,
    label: 'MENUITEMS.APPS.LIST.COURSES',
    icon: 'ti ti-book',
    subItems: [
      {
        id: 9,
        label: 'MENUITEMS.APPS.LIST.COURSES',
        link: '/apps/courses',
        parentId: 8,
      },
      {
        id: 10,
        label: 'MENUITEMS.APPS.LIST.COURSE_REVIEW',
        link: '/apps/course-review',
        parentId: 8,
      },
    ],
  },
  {
    id: 9,
    label: 'MENUITEMS.APPS.LIST.EVENT',
    icon: 'ti ti-calendar-event',
    link: '/apps/events',
    parentId: 8,
  },
  {
    id: 9,
    label: 'MENUITEMS.APPS.LIST.FAQS',
    icon: 'ti ti-help',
    link: '/apps/faqs',
    parentId: 8,
  },
  {
    id: 9,
    label: 'MENUITEMS.APPS.LIST.INSTRUCTORS',
    icon: 'ti ti-school',
    link: '/apps/instructors',
    parentId: 8,
  },
  {
    id: 9,
    label: 'MENUITEMS.APPS.LIST.MAIN_SLIDER',
    icon: 'ti ti-slideshow',
    link: '/apps/main-sliders',
    parentId: 8,
  },
  {
    id: 9,
    label: 'MENUITEMS.APPS.LIST.POSTS',
    icon: 'ti ti-article',
    link: '/apps/posts',
    parentId: 8,
  },
  {
    id: 2,
    label: 'MENUITEMS.APPS.LIST.PRODUCTS',
    icon: 'ti ti-shopping-cart',
    subItems: [
      {
        id: 9,
        label: 'MENUITEMS.APPS.LIST.PRODUCTS',
        link: '/apps/products',
        parentId: 8,
      },
      {
        id: 10,
        label: 'MENUITEMS.APPS.LIST.PRODUCT_REVIEW',
        link: '/apps/product-review',
        parentId: 8,
      },
    ],
  },
  {
    id: 23,
    label: 'MENUITEMS.APPS.LIST.TAGS',
    icon: 'ti ti-tag',
    link: '/apps/tags',
    parentId: 8,
  },
  {
    id: 23,
    label: 'MENUITEMS.APPS.LIST.USERS',
    icon: 'ti ti-user',
    link: '/apps/users',
    parentId: 8,
  },
  {
    id: 142,
    label: 'MENUITEMS.CHARTS.TEXT',
    icon: 'ti ti-chart-pie',
    subItems: [
      {
        id: 143,
        label: 'MENUITEMS.CHARTS.LIST.LINE',
        link: '/charts/apex-line',
        parentId: 142,
      },
      {
        id: 144,
        label: 'MENUITEMS.CHARTS.LIST.AREA',
        link: '/charts/apex-area',
        parentId: 142,
      },
      {
        id: 145,
        label: 'MENUITEMS.CHARTS.LIST.COLUMN',
        link: '/charts/apex-column',
        parentId: 142,
      },
      {
        id: 146,
        label: 'MENUITEMS.CHARTS.LIST.BAR',
        link: '/charts/apex-bar',
        parentId: 142,
      },
      {
        id: 147,
        label: 'MENUITEMS.CHARTS.LIST.MIXED',
        link: '/charts/apex-mixed',
        parentId: 142,
      },
      {
        id: 148,
        label: 'MENUITEMS.CHARTS.LIST.TIMELINE',
        link: '/charts/apex-timeline',
        parentId: 142,
      },
      {
        id: 149,
        label: 'MENUITEMS.CHARTS.LIST.CANDLSTICK',
        link: '/charts/apex-candlestick',
        parentId: 142,
      },
      {
        id: 150,
        label: 'MENUITEMS.CHARTS.LIST.BOXPLOT',
        link: '/charts/apex-boxplot',
        parentId: 142,
      },
      {
        id: 151,
        label: 'MENUITEMS.CHARTS.LIST.BUBBLE',
        link: '/charts/apex-bubble',
        parentId: 142,
      },
      {
        id: 152,
        label: 'MENUITEMS.CHARTS.LIST.SCATTER',
        link: '/charts/apex-scatter',
        parentId: 142,
      },
      {
        id: 153,
        label: 'MENUITEMS.CHARTS.LIST.HEATMAP',
        link: '/charts/apex-heatmap',
        parentId: 142,
      },
      {
        id: 154,
        label: 'MENUITEMS.CHARTS.LIST.TREEMAP',
        link: '/charts/apex-treemap',
        parentId: 142,
      },
      {
        id: 155,
        label: 'MENUITEMS.CHARTS.LIST.PIE',
        link: '/charts/apex-pie',
        parentId: 142,
      },
      {
        id: 156,
        label: 'MENUITEMS.CHARTS.LIST.RADIALBAR',
        link: '/charts/apex-radialbar',
        parentId: 142,
      },
      {
        id: 157,
        label: 'MENUITEMS.CHARTS.LIST.RADAR',
        link: '/charts/apex-radar',
        parentId: 142,
      },
      {
        id: 158,
        label: 'MENUITEMS.CHARTS.LIST.POLARAREA',
        link: '/charts/apex-polar',
        parentId: 142,
      },
    ],
  },
  {
    id: 161,
    label: 'MENUITEMS.ICONS.TEXT',
    icon: 'ti ti-icons',
    link: '/icons/bootstrap',
    parentId: 159,
  },
];
